# YOLOv5 ðŸš€ by Ultralytics, GPL-3.0 license
# README translation action to translate README.yolov5.md to Chinese as README.yolov5.zh-CN.md on any change to README.yolov5.md

name: Translate README

on:
  push:
    branches:
      - translate_readme  # replace with 'master' to enable action
    paths:
      - README.yolov5.md

jobs:
  Translate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      # ISO Language Codes: https://cloud.google.com/translate/docs/languages
      - name: Adding README - Chinese Simplified
        uses: dephraiim/translate-readme@main
        with:
          LANG: zh-CN
